apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-app
spec:
  replicas: 20
  selector:
    matchLabels:
      app: multi-app
  template:
    metadata:
      labels:
        app: multi-app
    spec:
      containers:
      - name: list-app
        image: localhost:5000/list
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: shared-data
          mountPath: /app/data
      - name: signup-app
        image: localhost:5000/signup
        ports:
        - containerPort: 5002
        volumeMounts:
        - name: shared-data
          mountPath: /app/data
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: voyager-pvc