apiVersion: v1
kind: Service
metadata:
  name: list-app-svc
spec:
  type: NodePort
  selector:
    app: multi-app
  ports:
  - name: list-port
    port: 8080
    targetPort: 5000
    nodePort: 81
---
apiVersion: v1
kind: Service
metadata:
  name: signup-app-svc
spec:
  type: NodePort
  selector:
    app: multi-app
  ports:
  - name: signup-port
    port: 8090
    targetPort: 5002
    nodePort: 82